export const googleMapLanguages = {
  Afrikaans: "af",
  Amharic: "am",
  Arabic: "ar",
  Azerbaijani: "az",
  Belarusian: "be",
  Bulgarian: "bg",
  Bengali: "bn",
  Bosnian: "bs",
  Catalan: "ca",
  Czech: "cs",
  Danish: "da",
  German: "de",
  Greek: "el",
  English: "en",
  "English (Australian)": "en-AU",
  "English (Great Britain)": "en-GB",
  Spanish: "es",
  "Spanish (Latin America)": "es-419",
  Estonian: "et",
  Basque: "eu",
  Farsi: "fa",
  Finnish: "fi",
  Filipino: "fil",
  French: "fr",
  "French (Canada)": "fr-CA",
  Galician: "gl",
  Gujarati: "gu",
  Hindi: "hi",
  Croatian: "hr",
  Hungarian: "hu",
  Armenian: "hy",
  Indonesian: "id",
  Icelandic: "is",
  Italian: "it",
  Hebrew: "iw",
  Japanese: "ja",
  Georgian: "ka",
  Kazakh: "kk",
  Khmer: "km",
  Kannada: "kn",
  Korean: "ko",
  Kyrgyz: "ky",
  Lao: "lo",
  Lithuanian: "lt",
  Latvian: "lv",
  Macedonian: "mk",
  Malayalam: "ml",
  Mongolian: "mn",
  Marathi: "mr",
  Malay: "ms",
  Burmese: "my",
  Nepali: "ne",
  Dutch: "nl",
  Norwegian: "no",
  Punjabi: "pa",
  Polish: "pl",
  Portuguese: "pt",
  "Portuguese (Brazil)": "pt-BR",
  "Portuguese (Portugal)": "pt-PT",
  Romanian: "ro",
  Russian: "ru",
  Sinhalese: "si",
  Slovak: "sk",
  Slovenian: "sl",
  Albanian: "sq",
  Serbian: "sr",
  Swedish: "sv",
  Swahili: "sw",
  Tamil: "ta",
  Telugu: "te",
  Thai: "th",
  Turkish: "tr",
  Ukrainian: "uk",
  Urdu: "ur",
  Uzbek: "uz",
  Vietnamese: "vi",
  Chinese: "zh",
  "Chinese (Simplified)": "zh-CN",
  "Chinese (Hong Kong)": "zh-HK",
  "Chinese (Traditional)": "zh-TW",
  Zulu: "zu",
} as const;
